infra:
    log_dir: ./ # where all the experiments are
    exp_name: hidisc # use the same name as the training experiment
    comment: patient_disc_dev # can use this to customize for each experiment
    seed: 1000
data:
    db_root:  /path/to/opensrh/
model:
    backbone: resnet50
    mlp_hidden: []
    num_embedding_out: 128
    train_alg: hidisc
eval:
    predict_batch_size: 128
    knn_batch_size: 1024
    ckpt_path: relative/path/to/checkpoint.ckpt # eg. hash_datetime_expname_comment/models/ckpt-epochXX-accXXX.ckpt
